### ISSUE TITLE
hot keys not working since update v0.16

### ISSUE THREAD

**Issue by remigius01** [nathan-b/colortoggle#20]
hot keys not working since update v0.16.

**Comment by remigius01** [comment]
I find an Old Version  v0.15. That work 
https://addons.mozilla.org/en-US/firefox/addon/color-toggle/versions/

**Comment by stephanfriedrich** [comment]
Please Fix it. +1

**Comment by heliac2000** [comment]
Change all "btWriteLog(...)" to "this.btWriteLog(...)" in chrome/content/colortoggle.js, thus hot key would be enabled.

**Comment by duguyipiao** [comment]
@heliac2000 It works. Thank you!

P.S. The **first** btWriteLog **shouldn't** be changed to this.btWriteLog. It is the definition of the function btWriteLog. Only change all "btWriteLog(...)" to "this.btWriteLog(...)" in chrome/content/colortoggle.js as stated by @heliac2000.

**Comment by polarka** [comment]
is there anywhere a compiled xpi available for FF with this fix?

**Comment by hlhodges** [comment]
I can't figure out which file to edit to apply heliac2000's solution. There is no "content" folder in my chrome folder, only userContent.css and a couple of example css files. The file colortoggle.js does not show up anywhere in the .mozilla sub-directory. I'm on Debian Linux. The filepath I'm looking through is /home/(user)/.mozilla/(profile name)/chrome.

**Comment by hlhodges** [comment]
I see, the .xpi file in the extensions folder is an archive. I extracted the files, edited colortoggle.js, and re-saved the files as an archive. 

Now, Firefox complains that the add-on isn't signed, and I had to set xpinstall.signatures.required in about:config to false to enable it. The extension is still unusable, though. The icon no longer appears on my toolbar, my hotkey doesn't work, and nothing happens when I click on Preferences. I've tried uninstalling and manually re-installing it; nothing changed. 

Am I doing this incorrectly?

**Comment by 4Jax** [comment]
Signed up just so I could say '**Big Thanks**' to **heliac2000** & **duguyipio** for this FIX !

Note to hlgodges on Linux:
Download the addon from Mozilla and save it to your desktop or wherever, open the .xpi archive and chase down the path that the boys above listed.  Follow their instructions.  There are many lines that have to be replaced so use search & replace option in your text editor, Save the text file... should get a notice from your archive manger to 'repack' the archive, say yes!

Now in Firefox install addon from file... select the .xpi you just repacked.

Works for me on Linux Mint v17.0x.

Good Luck!

**Comment by hlhodges** [comment]
Thanks 4Jax, but that sounds exactly like what I did. As I indicated in my previous post, the add-on became unusable after I edited it.

**Comment by 4Jax** [comment]
The difference is,  as you stated in your post you are trying to change the addon after it's been installed in the working Linux directory: "The filepath I'm looking through is /home/(user)/.mozilla/(profile name)/chrome."

You need to alter a fresh copy, make the changes, then install.
Verified works on my Linux Mint v17.x and latest FF version for Linux.

To make your life easier you can use the one I already fixed.  Just install it...

I'm new here so I'm not sure if my link will show up?

** Feb 2017 I fixed the link below:
https://www.dropbox.com/s/7d1yttb93crurb4/color_toggle-0.16-fx%20Hotkey%20Fix.xpi?dl=0

**Comment by 4Jax** [comment]
Hi,

Check out my reply.  I included my fixed .xpi that is verified working 
on my Linux box.

If the dropbox link doesn't show then here it is again: 
https://www.dropbox.com/s/7d1yttb93crurb4/color_toggle-0.16-fx%20Hotkey%20Fix.xpi?dl=0

Good Luck.

Peace.
Mike

**Comment by hlhodges** [comment]
I still can't install the add-on, even after I downloaded a fresh copy from addons.mozilla, edited colortoggle.js, and re-packaged the archive: 

7z a ../<extension_name>.xpi * -r

I still get an error: "This add-on could not be installed because it appears to be corrupt."

**Comment by 4Jax** [comment]
I can only recommend as I did before.  Uninstall the addon, reboot Firefox, install my version that I have already edited.

I've re-organized my Dropbox so that link is dead.

Here is the new link:

https://www.dropbox.com/s/7d1yttb93crurb4/color_toggle-0.16-fx%20Hotkey%20Fix.xpi?dl=0
